#!/usr/bin/env python2

"""Newer interface to socketfs sockets"""

class socket(object):
    def __init__(self, name, pid = None):
        self.name = name
        self.pid = pid

    def write(self, value):
        write(self.name, value, self.pid)
    send = write

    def read(self):
        return read(self.name)
    recv = read

class legacy(socket):
    def read(self):
        return read(self.name)[1]
    recv = read

def write(address, value, pid):
    set_path("/proc/socket/" + address, (pid, value))
send = write

def read(address):
    return get_path("/proc/socket/" + address)
recv = read
