#!/usr/bin/env python2

"""Newer interface to socketfs sockets"""

class socket(object):
    def __init__(self, name, pid = None):
        self.name = name
        self.pid = pid
        self.path = "/proc/socket" + name

        if name not in ls("/proc/socket"):
            self.write("you should not be reading this")
            self.read()

    def write(self, value):
        write(self.name, value, self.pid)
    send = write

    def read(self, default = ""):
        return read(self.name, default)
    recv = read

class legacy(socket):
    def read(self):
        return read(self.name)[1]
    recv = read

def write(address, value, pid):
    set_path("/proc/socket/" + address, (pid, value))
send = write

def read(address, default = ""):
    try:
        return get_path("/proc/socket/" + address)
    except:
        return default
recv = read
