#!/usr/bin/env python2

import ipc

def switch_init(initlevel):
	if initlevel != "socket" and\
	    initlevel in get_path("/etc/initmgr").keys():
		if "loud" in CIOS_MAGIC:
			printf("[INIT]", initlevel)
		
		for name, args in\
		    get_path("/etc/initmgr")[initlevel]["start"].items():
			if not process_exists(name):
				if "loud" in CIOS_MAGIC:
					printf("[START]", name)
				spawn(name, args = args.split(",")\
		   	    	    if args != [""] else () )
		for name in\
		    get_path("/etc/initmgr")[initlevel]["stop"].keys():
			if "loud" in CIOS_MAGIC:
				printf("[STOP]", name)
		    	killall(name)
	else:
		if "loud" in CIOS_MAGIC:
			printf("[FAIL]", initlevel)

def _main():
        socket = ipc.legacy("initmgr")

	if "loud" in CIOS_MAGIC:
		printf("[START] initmgr")
	yield

	socket.write("boot")

	while True:
		yield

		try:
			initlevel = socket.read()
		except:
			continue
		switch_init( initlevel )
